# Generated by Django 6.0.2 on 2026-02-11 16:57

import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "date_time",
                    models.DateTimeField(
                        validators=[events.validators.validate_future_date]
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("organizer_email", models.EmailField(max_length=254)),
                (
                    "games",
                    models.ManyToManyField(related_name="events", to="games.boardgame"),
                ),
            ],
            options={
                "ordering": ["date_time", "name"],
            },
        ),
    ]
