# Generated by Django 6.0.2 on 2026-02-12 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizer_email",
        ),
        migrations.AddField(
            model_name="event",
            name="current_players",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Текущ брой играчи"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_players",
            field=models.PositiveIntegerField(
                default=4,
                validators=[django.core.validators.MinValueValidator(2)],
                verbose_name="Максимален брой места",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_name",
            field=models.CharField(default="John Doe", max_length=100),
        ),
    ]
