# Generated by Django 6.0.2 on 2026-02-24 12:55

from django.db import migrations
from datetime import timedelta
from django.utils import timezone


def populate_sample_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    BoardGame = apps.get_model("games", "BoardGame")

    sample_games = list(BoardGame.objects.all()[:5])

    sample_events_data = [
        {
            "name": "Weekend Gaming Marathon",
            "description": "An all-day gaming event featuring various board games.",
            "date_time": timezone.now() + timedelta(days=7, hours=10),
            "location": "Community Center Hall",
            "organizer_name": "Game Masters Guild",
            "current_players": 5,
            "max_players": 10,
            "games": sample_games[0:2] if len(sample_games) >= 2 else [],
        },
        {
            "name": "Strategy Game Night",
            "description": "Focus on deep strategy games like Catan and Terraforming Mars.",
            "date_time": timezone.now() + timedelta(days=14, hours=18),
            "location": "Local Cafe - 'The Dice Cup'",
            "organizer_name": "Strategic Minds Club",
            "current_players": 3,
            "max_players": 6,
            "games": sample_games[1:3] if len(sample_games) >= 3 else [],
        },
        {
            "name": "Family Fun Day",
            "description": "Kid-friendly board games for all ages.",
            "date_time": timezone.now() + timedelta(days=21, hours=14),
            "location": "Public Library",
            "organizer_name": "Parents Play Group",
            "current_players": 8,
            "max_players": 15,
            "games": sample_games[2:4] if len(sample_games) >= 4 else [],
        },
        {
            "name": "Party Games Extravaganza",
            "description": "Loud and lively party games! Bring your friends!",
            "date_time": timezone.now() + timedelta(days=28, hours=19),
            "location": "Private Residence",
            "organizer_name": "Fun Seekers",
            "current_players": 10,
            "max_players": 12,
            "games": sample_games[3:5] if len(sample_games) >= 5 else [],
        },
        {
            "name": "Cooperative Challenge",
            "description": "Team up to beat the game! Pandemic and Gloomhaven focus.",
            "date_time": timezone.now() + timedelta(days=35, hours=17),
            "location": "Game Shop - 'Level Up'",
            "organizer_name": "Co-op Gamers",
            "current_players": 4,
            "max_players": 8,
            "games": sample_games[0:1] if len(sample_games) >= 1 else [],
        },
        {
            "name": "Abstract Games Meetup",
            "description": "Explore the beauty of abstract strategy games like Azul.",
            "date_time": timezone.now() + timedelta(days=42, hours=16),
            "location": "University Game Club",
            "organizer_name": "Mind Benders",
            "current_players": 2,
            "max_players": 4,
            "games": sample_games[4:5] if len(sample_games) >= 5 else [],
        },
        {
            "name": "Historical Wargames",
            "description": "Deep dives into historical wargames.",
            "date_time": timezone.now() + timedelta(days=49, hours=11),
            "location": "Veterans Hall",
            "organizer_name": "History Buffs",
            "current_players": 2,
            "max_players": 4,
            "games": [], # No specific game from current samples
        },
        {
            "name": "New Releases Playtest",
            "description": "Try out the latest board game releases.",
            "date_time": timezone.now() + timedelta(days=56, hours=19),
            "location": "Game Store - 'The Newbie'",
            "organizer_name": "Early Adopters",
            "current_players": 6,
            "max_players": 10,
            "games": sample_games[0:3] if len(sample_games) >= 3 else [],
        },
        {
            "name": "Eurogame Evening",
            "description": "Focus on popular Euro-style games.",
            "date_time": timezone.now() + timedelta(days=63, hours=18),
            "location": "Community Center - Room B",
            "organizer_name": "Eurogamers United",
            "current_players": 4,
            "max_players": 7,
            "games": sample_games[1:4] if len(sample_games) >= 4 else [],
        },
        {
            "name": "RPG & Board Game Night",
            "description": "A mix of role-playing and board games.",
            "date_time": timezone.now() + timedelta(days=70, hours=18),
            "location": "Local Pub - 'The Dragon's Breath'",
            "organizer_name": "Fantasy Fans",
            "current_players": 7,
            "max_players": 12,
            "games": sample_games[2:5] if len(sample_games) >= 5 else [],
        },
    ]

    for event_data in sample_events_data:
        games_for_event = event_data.pop("games")
        event = Event.objects.create(**event_data)
        if games_for_event:
            event.games.set(games_for_event)


def remove_sample_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    sample_event_names = [
        "Weekend Gaming Marathon", "Strategy Game Night", "Family Fun Day",
        "Party Games Extravaganza", "Cooperative Challenge", "Abstract Games Meetup",
        "Historical Wargames", "New Releases Playtest", "Eurogame Evening",
        "RPG & Board Game Night"
    ]
    for name in sample_event_names:
        Event.objects.filter(name=name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("games", "0003_populate_sample_games"),
    ]

    operations = [
        migrations.RunPython(populate_sample_events, remove_sample_events),
    ]
