# Generated by Django 6.0.2 on 2026-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_event_organizer_email_event_current_players_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organizer_name",
            field=models.CharField(max_length=100),
        ),
    ]
