# Generated by Django 6.0.2 on 2026-04-12 11:36

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    result = Group.objects.get_or_create(name="Members")
    members_group = result[0]
    member_perms_codenames = [
        "add_gamereview",
        "change_gamereview",
        "delete_gamereview",
        "add_usercollection",
        "change_usercollection",
        "delete_usercollection",
        "view_boardgame",
        "view_event",
        "view_gamereview",
    ]
    for codename in member_perms_codenames:
        perm = Permission.objects.filter(codename=codename).first()
        if perm:
            members_group.permissions.add(perm)

    result = Group.objects.get_or_create(name="Moderators")
    moderators_group = result[0]
    mod_perms_codenames = [
        "add_boardgame",
        "change_boardgame",
        "delete_boardgame",
        "view_boardgame",
        "add_event",
        "change_event",
        "delete_event",
        "view_event",
        "add_gamereview",
        "change_gamereview",
        "delete_gamereview",
        "view_gamereview",
        "add_usercollection",
        "change_usercollection",
        "delete_usercollection",
    ]
    for codename in mod_perms_codenames:
        perm = Permission.objects.filter(codename=codename).first()
        if perm:
            moderators_group.permissions.add(perm)


def remove_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Members", "Moderators"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("reviews", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
