# Generated by Django 6.0.2 on 2026-02-24 12:45

from django.db import migrations


def populate_genres(apps, schema_editor):
    Genre = apps.get_model("games", "Genre")
    genres_to_add = [
        "Strategy", "Family", "Party", "Thematic", "Abstract",
        "Wargame", "Economic", "Card Game", "Legacy", "Cooperative"
    ]
    for genre_name in genres_to_add:
        Genre.objects.get_or_create(name=genre_name)


def remove_genres(apps, schema_editor):
    Genre = apps.get_model("games", "Genre")
    genres_to_remove = [
        "Strategy", "Family", "Party", "Thematic", "Abstract",
        "Wargame", "Economic", "Card Game", "Legacy", "Cooperative"
    ]
    for genre_name in genres_to_remove:
        Genre.objects.filter(name=genre_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_genres, remove_genres),
    ]
