# Generated by Django 6.0.2 on 2026-02-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgame",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
