# Generated by Django 6.0.2 on 2026-02-24 12:55

from django.db import migrations
from datetime import date


def populate_sample_games(apps, schema_editor):
    BoardGame = apps.get_model("games", "BoardGame")
    Genre = apps.get_model("games", "Genre")

    strategy_genre, _ = Genre.objects.get_or_create(name="Strategy")
    family_genre, _ = Genre.objects.get_or_create(name="Family")
    party_genre, _ = Genre.objects.get_or_create(name="Party")
    thematic_genre, _ = Genre.objects.get_or_create(name="Thematic")
    card_game_genre, _ = Genre.objects.get_or_create(name="Card Game")

    sample_games_data = [
        {
            "title": "Catan",
            "release_date": date(1995, 1, 1),
            "rating": 4.5,
            "min_players": 3,
            "max_players": 4,
            "description": "A classic strategy game of trading and building.",
            "image_url": "",
            "genre": strategy_genre,
        },
        {
            "title": "Ticket to Ride",
            "release_date": date(2004, 1, 1),
            "rating": 4.0,
            "min_players": 2,
            "max_players": 5,
            "description": "A cross-country train adventure game.",
            "image_url": "",
            "genre": family_genre,
        },
        {
            "title": "Codenames",
            "release_date": date(2015, 1, 1),
            "rating": 4.7,
            "min_players": 2,
            "max_players": 8,
            "description": "A word association game for two teams.",
            "image_url": "",
            "genre": party_genre,
        },
        {
            "title": "Gloomhaven",
            "release_date": date(2017, 1, 1),
            "rating": 4.9,
            "min_players": 1,
            "max_players": 4,
            "description": "A cooperative dungeon-crawling board game.",
            "image_url": "",
            "genre": thematic_genre,
        },
        {
            "title": "Wingspan",
            "release_date": date(2019, 1, 1),
            "rating": 4.6,
            "min_players": 1,
            "max_players": 5,
            "description": "A competitive, medium-weight, card-driven, engine-building board game.",
            "image_url": "",
            "genre": family_genre,
        },
        {
            "title": "Terraforming Mars",
            "release_date": date(2016, 1, 1),
            "rating": 4.8,
            "min_players": 1,
            "max_players": 5,
            "description": "A game about corporations terraforming Mars.",
            "image_url": "",
            "genre": strategy_genre,
        },
        {
            "title": "7 Wonders",
            "release_date": date(2010, 1, 1),
            "rating": 4.2,
            "min_players": 2,
            "max_players": 7,
            "description": "A card drafting game of building ancient civilizations.",
            "image_url": "",
            "genre": card_game_genre,
        },
        {
            "title": "Azul",
            "release_date": date(2017, 1, 1),
            "rating": 4.3,
            "min_players": 2,
            "max_players": 4,
            "description": "A tile-placement game for two to four players.",
            "image_url": "",
            "genre": card_game_genre,
        },
        {
            "title": "Pandemic",
            "release_date": date(2007, 1, 1),
            "rating": 4.1,
            "min_players": 2,
            "max_players": 4,
            "description": "A cooperative game about stopping outbreaks of diseases.",
            "image_url": "",
            "genre": card_game_genre,
        },
        {
            "title": "Splendor",
            "release_date": date(2014, 1, 1),
            "rating": 3.9,
            "min_players": 2,
            "max_players": 4,
            "description": "A game of gem collecting and renaissance merchant building.",
            "image_url": "",
            "genre": family_genre,
        },
    ]

    for game_data in sample_games_data:
        genre = game_data.pop("genre")
        BoardGame.objects.get_or_create(title=game_data["title"], defaults={"genre": genre, **game_data})


def remove_sample_games(apps, schema_editor):
    BoardGame = apps.get_model("games", "BoardGame")
    sample_game_titles = [
        "Catan", "Ticket to Ride", "Codenames", "Gloomhaven", "Wingspan",
        "Terraforming Mars", "7 Wonders", "Azul", "Pandemic", "Splendor"
    ]
    for title in sample_game_titles:
        BoardGame.objects.filter(title=title).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_populate_genres"),
    ]

    operations = [
        migrations.RunPython(populate_sample_games, remove_sample_games),
    ]
