# Generated by Django 6.0.2 on 2026-02-18 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_boardgame_description_alter_boardgame_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgame",
            name="rating",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
